### ISSUE TITLE
Incorrect return type of a Java method

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#123]
Talk is less, let's see the test case ;)

```
type StringBuffer = java.lang.StringBuffer;
let appendTo (c : Char) (buf : StringBuffer) : StringBuffer =
    buf.append(c);

'a' `appendTo` (new java.lang.StringBuffer( ))
```

In Java's official documents, the return type of `append` is `java.lang.StringBuffer`, but it seems that compiler believes it should be `java.lang.AbstractStringBuilder`.

If you tried to wrap it like this

```
type StringBuffer = java.lang.StringBuffer;
let appendTo (c : Char) (buf : StringBuffer) : StringBuffer =
    { buf.append(c); buf }; 

'a' `appendTo` (new java.lang.StringBuffer( ))
```

`javac` will complain about `java.lang.AbstractStringBuilder` is private.

**Comment by bixuanzju** [comment]
@lihuanglx Can you look at it? I suspect something wrong in `TypeServer`

**Comment by bixuanzju** [comment]
@zonyitoo This seems like a bug in JDK, see https://community.oracle.com/thread/1758369

**Comment by zonyitoo** [comment]
@bixuanzju Seem that I am very lucky. But in this thread, they said this problem actually happens in JDK1.5/1.6. I am already using JDK1.8. So the problem remain existent?

But why the second example still report errors? Seems like the second one is the solution in that thread.

**Comment by bixuanzju** [comment]
@zonyitoo You can try the following snippet, which basically query the return type of Java method call

``` java
Class<?> c = Class.forName("java.lang.StringBuffer");
Method[] mList = c.getMethods();

for (int i = 0; i < mList.length; i++) {
  if (mList[i].getName() == "append" && mList[i].getParameterTypes().length == 1) {
    System.out.println("=====");
    System.out.println(mList[i].getParameterTypes()[0].getCanonicalName());
    System.out.println(mList[i].getReturnType().getName());
  }
}
```

It outputs

```
=====
char[]
java.lang.AbstractStringBuilder
=====
int
java.lang.AbstractStringBuilder
=====
char
java.lang.AbstractStringBuilder
=====
char
java.lang.StringBuffer
=====
int
java.lang.StringBuffer
=====
...
```

You can see, given argument type `char`, the return type can be `java.lang.AbstractStringBuilder`, or `java.lang.StringBuffer`, and our `TypeServer` will retrieve the first type it finds appropriate, which is `java.lang.AbstractStringBuilder` in this example.

**Comment by zonyitoo** [comment]
@bixuanzju Indeed, I got the result, too.

```
char
java.lang.AbstractStringBuilder
=====
char
java.lang.StringBuffer
```

Why this happens? Why it allows the same method overloaded with different return type?

The following snippet actually works with my javac.

``` java
StringBuffer buf = new StringBuffer();
buf.append("abc").append('d').append("efg");
System.out.println(buf.toString());
```

**Comment by brunocdsoliveira** [comment]
So, am I right that you are getting _two_ results for the query? That is for the overloaded method with a char argument, you are getting 2 possible return types?

If so, is it possible to detect this situation, compare the two resulting types ("java.lang.AbstractStringBuilder" and "java.lang.StringBuffer" in this case), and return the entry that gives you a public type (or may find some better metric to compare types)?

**Comment by zonyitoo** [comment]
@brunocdsoliveira This problem not only happens on `StringBuffer`, but also on `StringBuilder`. And I don't think they are alone.

The return type of `StringBuilder.append` may be `java.lang.Appendable`, which is public.

**Comment by zonyitoo** [comment]
Also, because of #113 , it becomes a little bit hard to use these APIs, because

```
{
   let builder = new java.lang.StringBuilder( );
   builder.append('a');
   -- Error, I have lost the builder
   builder.append('b');
}
```

**Comment by brunocdsoliveira** [comment]
@zonyitoo I understand that, but you haven't answered my question.

**Comment by bixuanzju** [comment]
@zonyitoo @brunocdsoliveira I fixed that. Need to check if the returned type is public

**Comment by brunocdsoliveira** [comment]
@zonyitoo As I mentioned in #113 I think you can get around the issue of losing the builder by explicitly putting parenthesis in the expression.

**Comment by zonyitoo** [comment]
@brunocdsoliveira Sorry, Dr. Oliveira. Yes, query will return more than one results. After doing some searching on the web, it seems that this problem lasted about a decade. But still not sure that the problem in JDK is related to this problem.

**Comment by bixuanzju** [comment]
@zonyitoo Is the new commit fix for you?

**Comment by zonyitoo** [comment]
@bixuanzju Yes, it works for `StringBuilder`. But I think it is just a temporary workaround.

**Comment by bixuanzju** [comment]
@zonyitoo Maybe. But that's on JDK. If the return types for the same argument type is more than one and are all public, how can we be sure which one we wants?

**Comment by zonyitoo** [comment]
@bixuanzju How about adding a new feature to embed Java code directly into the generated Java file?

Such as

```
type HashMap[K, V] = java.util.HashMap[K, V];

@java
let newHashMap[K, V] : HashMap[K, V] = {
    return new java.util.HashMap<K, V>();
};
```

This feature also enables the possibility of constructing generic Java types. Just for brainstorming ;)

**Comment by bixuanzju** [comment]
That's interesting. Create a feature request and let's close this issue unless we find another counterexample.

**Comment by zonyitoo** [comment]
@bixuanzju I have already found another one for you, the `StringBuilder` (not `StringBuffer`). ;)

**Comment by bixuanzju** [comment]
@zonyitoo That's so confusing indeed!

@brunocdsoliveira Does Java allow overloading on functions's return type?

**Comment by brunocdsoliveira** [comment]
@bixuanzju no it doesn't. So I am not sure if it is a bug, or maybe some JVM (not Java) feature.

**Comment by zonyitoo** [comment]
@bixuanzju @brunocdsoliveira It may be a Java feature, check this link: https://today.java.net/pub/a/today/2008/07/31/return-type-based-method-overloading.html

**Comment by zonyitoo** [comment]
I think the two versions of `append`s comes from overriding, in the other word, the one that returns `java.lang.AbstractStringBuilder` is defined in `AbstractStringBuilder`. `StringBuffer` extends `AbstractStringBuilder` and override this function, which makes it returns `java.lang.StringBuffer`.

It is possible to call parent's methods by `super` in children's override methods.

**Comment by bixuanzju** [comment]
@zonyitoo @brunocdsoliveira StackOverflow is awesome!

http://stackoverflow.com/questions/29100438/reflection-api-give-overloading-on-functions-return-type/29100581#29100581

**Comment by zonyitoo** [comment]
I think a possible way to solve this is to filter those methods that have been overridden (including Interfaces).

**Comment by zonyitoo** [comment]
@bixuanzju Great!

**Comment by bixuanzju** [comment]
@zonyitoo Final attack! Have a try

**Comment by zonyitoo** [comment]
@bixuanzju Excellent! Works very well!
